### ISSUE TITLE
SHM size inadequate for planet

### ISSUE THREAD

**Issue by jimmyjones2** [Magellium/osmtilemaker#2]
The docker container is started with 256MB SHM, but I needed about 3GB to render the planet. Maybe add a note to the docs?

I had to add printing of exception details to gen-tile.py to figure this out!

**Comment by audour** [comment]
Hi @jimmyjones2,
Sorry for delay, I've not been notified of your comment, now it should be ok.
Mmmh it's strange because I used 256MB SHM to render planet between MINZOOM=1 & MAXZOOM=12 without problems.
Maybe you could propose documentation/gen-tile.py improvements through a pull request ?

**Comment by audour** [comment]
Following your suggestion, I've added a note to the docs and closed the issue. Thanks.
