### ISSUE TITLE
Error when rendering tiles: RuntimeError: Postgis Plugin: Null connection

### ISSUE THREAD

**Issue by centic9** [Magellium/osmtilemaker#6]
When following the steps in the README with default configuration (only pbf-file and boundin-box are set differently), I get the following strange error at the step where tiles are actually rendered.

```
ERROR:root:message
Traceback (most recent call last):
  File "/docker_mounted_volumes/sources/scripts/gen-tile.py", line 136, in loop
    self.render_tile(tile_uri, x, y, z)
  File "/docker_mounted_volumes/sources/scripts/gen-tile.py", line 116, in render_tile
    mapnik.render(self.m, im)
RuntimeError: Postgis Plugin: Null connection
genTile LOG> 2022-03-25 09:58:10: line 139: ERROR: Exception generating tile: /docker_mounted_volumes/tiles/9/269/165.png, 9, 269, 165
ERROR:root:message
Traceback (most recent call last):
  File "/docker_mounted_volumes/sources/scripts/gen-tile.py", line 136, in loop
    self.render_tile(tile_uri, x, y, z)
  File "/docker_mounted_volumes/sources/scripts/gen-tile.py", line 116, in render_tile
    mapnik.render(self.m, im)
RuntimeError: Postgis Plugin: Null connection
ERROR:genTile:Exception generating tile: /docker_mounted_volumes/tiles/9/269/165.png, 9, 269, 165
genTile LOG> 2022-03-25 09:58:10: line 139: ERROR: Exception generating tile: /docker_mounted_volumes/tiles/7/67/41.png, 7, 67, 41
ERROR:genTile:Exception generating tile: /docker_mounted_volumes/tiles/7/67/41.png, 7, 67, 41
genTile LOG> 2022-03-25 09:59:32: line 149: INFO: Trentino: 1, 1, 0,
INFO:genTile:Trentino: 1, 1, 0,
```

Mapnik is at 3.1.0, Python-mapnik at 3.0.23:

```
$ pip3 list | grep map
mapnik             3.0.23
```

```
$ dpkg --list | grep map
ii  libmapnik3.1                           3.1.0+ds-1                     amd64        C++ toolkit for developing GIS applications (libraries)
ii  mapnik-utils                           3.1.0+ds-1                     amd64        C++ toolkit for developing GIS applications (utilities)
ii  python3-mapnik                         1:0.0~20200224-7da019cf9-3     amd64        Python 3 interface to the mapnik library
```

I could not find any error-log from postgres

I found https://github.com/mapnik/mapnik-support/issues/60#issuecomment-178138451 which mentions that such an error-message might be a postgres-error that is not reported well, but it seems mapnik 3.1.0 is in place already here and thus low-level errors should not be hidden here.

Anything else that I can try to make tile-generation work here?

**Comment by centic9** [comment]
Setting RENDERING_THREADS to a lower values seems to work without the error. 8 seems to work fine for me.

Maybe the default of RENDERING_THREADS=12 does not work well with the default of the pool-size in mapnik of "max_size=10"?

Should the script configure a different "max_size" for the connection-pool in Mapnik or a different number of RENDERING_THREADS?

**Comment by audour** [comment]
Thanks for creating this issue. Happy to know that it worked.
As we do not have a sure answer, maybe we could just lower the default of RENDERING_THREADS=12 to 4 which is more common ?
If somebody encounters the same error message `Postgis Plugin: Null connection`, your issue could help.
If it's ok for you, don't hesitate to make a PR. Or I can make the update and close this issue.

**Comment by centic9** [comment]
I created PR #7 to adjust threads to 10, this seems to work fine and still ensures good parallelism on powerful machines.

I also created PR #8 with some smaller adjustments to the gen_tile.py which I found useful when looking for problems with tile-generation.

**Comment by audour** [comment]
Thanks @centic9 for your PRs ! I've merged them.
