### ISSUE TITLE
High-res tiles

### ISSUE THREAD

**Issue by philippbosch** [Magellium/osmtilemaker#9]
A question, not an issue …

Have you tried generating [high-res tiles](https://wiki.openstreetmap.org/wiki/High-resolution_tiles) with osmtilemaker and can share how you did it by any chance?

Thanks for the great project!

**Comment by audour** [comment]
Hi, tanks for your message.
I've no tried generating retina tiles with osmtilemaker but it would be great !
Have you explored mapnik/openstreetmap-carto doc or issues about that ? I don't have time currently but don't hesitate to contribute by sharing search results or code.

**Comment by audour** [comment]
Without any updates for 5 months, I close the issue. Thanks for your contribution.
